/**
 * Recursive partial-heading collector.
 *
 * When a docs page includes `<Render file="..." />`, Astro's
 * `render(entry).headings` only contains headings from the parent
 * entry's own source — headings inside the partial are invisible to
 * the TOC. This module splices partial headings into the parent's
 * heading list in document order, recursively (partials can include
 * other partials).
 *
 * Strategy:
 *
 *   1. Parse the entry's raw MDX body with Sätteri's `mdxToMdast` —
 *      the same parser that renders the site.
 *   2. Walk the tree in source order, collecting two kinds of "slots":
 *      `heading` nodes and `mdxJsxFlowElement`/`mdxJsxTextElement`
 *      nodes named `Render`.
 *   3. For heading slots, consume the next heading from Astro's
 *      `render(entry).headings` array (preserving exact text/slug).
 *   4. For `Render` slots, read literal JSX attributes (`file`, `product`),
 *      resolve the partial id via a user-supplied resolver, call
 *      `getEntry("partials", id)`, then `render(partial)` for its own
 *      headings — recursively merging nested `<Render>` calls.
 *   5. Append any unconsumed original headings (e.g. `footnote-label`
 *      generated by the remark footnotes plugin, which has no
 *      corresponding `heading` node in the source AST).
 *
 * Limitations (by design):
 *
 *   - Dynamic `file={expr}` attributes are ignored — the collector
 *     only resolves literal string values.
 *   - Headings produced by runtime component output are invisible to this
 *     collector and require application-level handling.
 *   - Missing partials are silently skipped — `Render.astro` owns
 *     the build-time "not found" error with its helpful suggestions.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Heading {
  depth: number;
  text: string;
  slug: string;
}

export interface PartialHeadingOptions {
  /**
   * Resolve a `<Render>` invocation to a partial collection id.
   *
   * Receives the literal attribute values extracted from the JSX node.
   * Return the partial id (path relative to `src/content/partials/`
   * without extension), or `undefined` to skip this invocation.
   *
   * Default: returns `file` as-is (Nimbus starter convention).
   */
  resolvePartialId?: (attrs: {
    file: string | undefined;
    product: string | undefined;
  }) => string | undefined;
}

// ---------------------------------------------------------------------------
// Sätteri AST helpers (minimal — no @types/mdast coupling)
// ---------------------------------------------------------------------------

interface MdNode {
  type: string;
  name?: string | null;
  depth?: number;
  value?: string;
  attributes?: unknown[];
  children?: MdNode[];
  position?: {
    start?: { offset?: number; line?: number; column?: number };
    end?: { offset?: number; line?: number; column?: number };
  };
}

interface JsxAttribute {
  type: string;
  name: string;
  value:
    | string
    | { type: string; value: string }
    | null
    | undefined;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Merge partial headings into the parent entry's heading list.
 *
 * @param body - The entry's raw MDX body (`entry.body`).
 * @param astroHeadings - Headings from `render(entry).headings`.
 * @param getEntry - Astro's `getEntry` from `astro:content`.
 * @param render - Astro's `render` from `astro:content`.
 * @param options - Optional resolver for custom `<Render>` id conventions.
 */
export async function mergePartialHeadings(
  body: string | undefined,
  astroHeadings: Heading[],
  getEntry: (collection: string, id: string) => Promise<unknown>,
  render: (entry: unknown) => Promise<{ headings: Heading[] }>,
  options?: PartialHeadingOptions,
): Promise<Heading[]> {
  const { mdxToMdast } = await import("satteri");
  return mergePartialHeadingsWithParser(
    body,
    astroHeadings,
    getEntry,
    render,
    (source) => mdxToMdast(source) as unknown as MdNode,
    options,
  );
}

export async function mergePartialHeadingsWithParser(
  body: string | undefined,
  astroHeadings: Heading[],
  getEntry: (collection: string, id: string) => Promise<unknown>,
  render: (entry: unknown) => Promise<{ headings: Heading[] }>,
  parse: (body: string) => MdNode,
  options?: PartialHeadingOptions,
): Promise<Heading[]> {
  return mergePartialHeadingsInternal(
    body,
    astroHeadings,
    getEntry,
    render,
    parse,
    options,
    new Set(),
  );
}

async function mergePartialHeadingsInternal(
  body: string | undefined,
  astroHeadings: Heading[],
  getEntry: (collection: string, id: string) => Promise<unknown>,
  render: (entry: unknown) => Promise<{ headings: Heading[] }>,
  parse: (body: string) => MdNode,
  options: PartialHeadingOptions | undefined,
  seen: Set<string>,
): Promise<Heading[]> {
  if (!body) return astroHeadings;

  let tree: MdNode;
  try {
    tree = parse(body);
  } catch {
    // If the body doesn't parse, fall back to Astro's headings —
    // the build will fail elsewhere with a proper diagnostic.
    return astroHeadings;
  }

  const slots = collectSlots(tree);
  const resolve = options?.resolvePartialId ?? defaultResolver;

  const result: Heading[] = [];
  let headingIdx = 0;

  for (const slot of slots) {
    if (slot.kind === "heading") {
      // Consume the next Astro heading. Astro's heading list is in
      // document order and should align 1:1 with source `heading`
      // nodes. If counts mismatch (e.g. a heading generated by a
      // remark plugin with no source node), the extras are appended
      // after the loop.
      if (headingIdx < astroHeadings.length) {
        result.push(astroHeadings[headingIdx]!);
        headingIdx++;
      }
    } else {
      // Render slot — resolve and recurse.
      const partialHeadings = await collectFromPartial(
        slot.file,
        slot.product,
        getEntry,
        render,
        parse,
        resolve,
        seen,
      );
      result.push(...partialHeadings);
    }
  }

  // Append any remaining Astro headings that had no corresponding
  // source `heading` node (e.g. `footnote-label` from the footnotes
  // remark plugin, or headings injected by other remark plugins).
  while (headingIdx < astroHeadings.length) {
    result.push(astroHeadings[headingIdx]!);
    headingIdx++;
  }

  return result;
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

type Slot =
  | { kind: "heading"; offset: number }
  | { kind: "render"; offset: number; file: string | undefined; product: string | undefined };

function collectSlots(root: MdNode): Slot[] {
  const slots: Slot[] = [];

  function walk(node: MdNode): void {
    if (node.type === "heading") {
      slots.push({
        kind: "heading",
        offset: node.position?.start?.offset ?? 0,
      });
      // Don't recurse into heading children — they're text/emphasis
      // nodes, not heading-level slots.
      return;
    }

    if (
      (node.type === "mdxJsxFlowElement" ||
        node.type === "mdxJsxTextElement") &&
      node.name === "Render"
    ) {
      const attrs = parseRenderAttributes(node.attributes);
      slots.push({
        kind: "render",
        offset: node.position?.start?.offset ?? 0,
        file: attrs.file,
        product: attrs.product,
      });
      // Don't recurse into Render children — the partial's own
      // headings are collected when we render it.
      return;
    }

    // Recurse into children for nested headings/renders.
    if (node.children) {
      for (const child of node.children) walk(child);
    }
  }

  if (root.children) {
    for (const child of root.children) walk(child);
  }

  slots.sort((a, b) => a.offset - b.offset);
  return slots;
}

function parseRenderAttributes(
  attributes: unknown,
): { file: string | undefined; product: string | undefined } {
  let file: string | undefined;
  let product: string | undefined;

  if (!Array.isArray(attributes)) return { file, product };

  for (const attr of attributes as JsxAttribute[]) {
    if (attr.type !== "mdxJsxAttribute") continue;
    const val = attr.value;
    if (typeof val !== "string") continue; // skip expression values
    if (attr.name === "file") file = val;
    if (attr.name === "product") product = val;
  }

  return { file, product };
}

function defaultResolver(attrs: {
  file: string | undefined;
  product: string | undefined;
}): string | undefined {
  return attrs.file;
}

async function collectFromPartial(
  file: string | undefined,
  product: string | undefined,
  getEntry: (collection: string, id: string) => Promise<unknown>,
  render: (entry: unknown) => Promise<{ headings: Heading[] }>,
  parse: (body: string) => MdNode,
  resolve: (attrs: {
    file: string | undefined;
    product: string | undefined;
  }) => string | undefined,
  seen: Set<string>,
): Promise<Heading[]> {
  const id = resolve({ file, product });
  if (!id) return [];

  // Cycle guard — a partial that includes itself (directly or
  // transitively) would infinite-loop. Throw so the build fails
  // with a readable trace instead of hanging.
  if (seen.has(id)) {
    const chain = [...seen, id].join(" -> ");
    throw new Error(
      `[nimbus-docs] Circular <Render> partial include: ${chain}. ` +
        `Check for a partial that renders itself directly or transitively.`,
    );
  }

  let partial: unknown;
  try {
    partial = await getEntry("partials", id);
  } catch {
    return [];
  }
  if (!partial) return [];

  seen.add(id);

  let rendered: { headings: Heading[] };
  try {
    rendered = await render(partial);
  } catch {
    seen.delete(id);
    return [];
  }

  // The partial's own headings from Astro's render() — these are
  // already in document order for that partial's source.
  const partialHeadings = rendered.headings;

  // Now check if the partial itself contains nested <Render> calls
  // that contribute additional headings. We need the partial's body
  // to parse for nested slots.
  const partialBody = (partial as { body?: string }).body;
  if (!partialBody) {
    seen.delete(id);
    return partialHeadings;
  }

  // Parse the partial's body to find nested Render slots and merge
  // their headings into the partial's own heading list.
  const merged = await mergePartialHeadingsInternal(
    partialBody,
    partialHeadings,
    getEntry,
    render,
    parse,
    { resolvePartialId: resolve },
    seen,
  );

  seen.delete(id);
  return merged;
}
