/**
 * The **authoring** category: the shipped `lint` engine adapted into the
 * `check` envelope — same content dirs, same `.nimbus/lint.json` severities,
 * same rules, each `Diagnostic` mapped through `fromDiagnostic`. Unlike `lint`,
 * a zero-`.mdx` project is NOT an error: a config-only `check` must still pass.
 *
 * The core rules always run (so the scope is always `evaluated`). Coverage that
 * `astro build` materializes — opt-in rule enablement (`.nimbus/lint.json`) and
 * `internal-link`'s route truth (`.nimbus/routes.json`) — becomes a `note` when
 * absent, never a warning and never a silent false-green pass.
 */

import fs from "node:fs";
import path from "node:path";

import {
  findMdxFiles,
  lintPaths,
  validateLintOptions,
  IMPLEMENTED_CODES,
  type CollectionsConfig,
  type RulesConfig,
} from "../lint/index.js";
import { fromDiagnostic, type CheckFinding, type Note, type ScopeReport } from "./finding.js";

export function checkAuthoring(cwd: string): ScopeReport {
  const findings: CheckFinding[] = [];
  const notes: Note[] = [];
  const hasLintJson = fs.existsSync(path.join(cwd, ".nimbus", "lint.json"));
  const { config, error } = loadMaterializedConfig(cwd);

  if (error) {
    findings.push({
      scope: "authoring",
      code: "nimbus/lint-config-invalid",
      severity: "error",
      file: ".nimbus/lint.json",
      message: `${error} Delete the file (it's regenerated by \`astro build\`) or fix it.`,
      fixable: false,
    });
  }

  const files = findMdxFiles([path.join(cwd, "src", "content")]);
  if (files.length === 0) {
    return { scope: "authoring", findings, notes, evaluated: true };
  }

  let effective = config;
  if (!hasLintJson) {
    notes.push({
      code: "nimbus/authoring-optin-skipped",
      reason:
        "opt-in authoring rules not evaluated — their enablement is materialized by `astro build` into `.nimbus/lint.json`, which doesn't exist yet. Core rules still ran.",
      requiresBuild: true,
    });
  } else if (
    !error &&
    internalLinkEnabled(config) &&
    !fs.existsSync(path.join(cwd, ".nimbus", "routes.json"))
  ) {
    notes.push({
      code: "nimbus/internal-link-skipped",
      reason:
        "link checking skipped — `nimbus/internal-link` resolves against the route map `astro build` materializes into `.nimbus/routes.json`, which doesn't exist yet. Other authoring rules still ran.",
      requiresBuild: true,
    });
    // Noted structurally above — disable the rule so it doesn't also run and
    // write its own skip warning to stderr.
    effective = withRuleDisabled(config, "nimbus/internal-link");
  }

  for (const d of lintPaths(files, cwd, effective)) findings.push(fromDiagnostic(d));
  return { scope: "authoring", findings, notes, evaluated: true };
}

function withRuleDisabled(
  config: MaterializedConfig,
  code: keyof RulesConfig,
): MaterializedConfig {
  const collections: CollectionsConfig = {};
  for (const [name, collection] of Object.entries(config.collections)) {
    collections[name] = collection.rules
      ? { ...collection, rules: { ...collection.rules, [code]: "off" } }
      : collection;
  }
  return {
    ...config,
    rules: { ...config.rules, [code]: "off" },
    collections,
  };
}

function internalLinkEnabled(config: MaterializedConfig): boolean {
  const code = "nimbus/internal-link";
  const settings: unknown[] = [(config.rules as Record<string, unknown>)[code]];
  for (const collection of Object.values(config.collections)) {
    const rules = collection.rules as Record<string, unknown> | undefined;
    if (rules) settings.push(rules[code]);
  }
  return settings.some((setting) => {
    const severity = Array.isArray(setting) ? setting[0] : setting;
    return severity === "error" || severity === "warn";
  });
}

export interface MaterializedConfig {
  rules: RulesConfig;
  collections: CollectionsConfig;
  site?: string;
}

export interface LoadMaterializedResult {
  config: MaterializedConfig;
  /** Non-null when the file exists but couldn't be parsed/validated. */
  error: string | null;
}

/**
 * Read the materialized lint config from `.nimbus/lint.json`, distinguishing
 * three cases so callers never confuse "no config yet" with "broken config":
 * absent → defaults + `error: null`; present-but-invalid → defaults + `error`
 * set; valid → the materialized severities. Returns the error (rather than
 * process-exiting like `lint`) so the envelope can carry it as a finding.
 */
export function loadMaterializedConfig(cwd: string): LoadMaterializedResult {
  const file = path.join(cwd, ".nimbus", "lint.json");
  const rel = ".nimbus/lint.json";
  let raw: string;
  try {
    raw = fs.readFileSync(file, "utf8");
  } catch {
    return { config: { rules: {}, collections: {} }, error: null };
  }

  let parsed: { rules?: unknown; collections?: unknown; site?: unknown };
  try {
    parsed = JSON.parse(raw) as typeof parsed;
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return {
      config: { rules: {}, collections: {} },
      error: `${rel} is not valid JSON — ${detail}.`,
    };
  }

  try {
    const validated = validateLintOptions(
      { rules: parsed.rules, collections: parsed.collections },
      IMPLEMENTED_CODES,
    );
    const site = typeof parsed.site === "string" ? parsed.site : undefined;
    return {
      config: { rules: validated.rules, collections: validated.collections, site },
      error: null,
    };
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return { config: { rules: {}, collections: {} }, error: `${rel} is invalid — ${detail}.` };
  }
}
