// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// ai-memory Docs (English) — unofficial English mirror of https://github.com/akitaonrails/ai-memory
// Generated by scripts/new-en-mirror.cjs — do not edit by hand; re-run to refresh.
export default defineConfig({
	site: undefined,
	base: process.env.DOCS_BASE || '/',
	integrations: [
		starlight({
			title: "ai-memory Docs (English)",
			description: "Unofficial English mirror of the ai-memory docs. Long-term memory for AI coding agents.",
			defaultLocale: 'root',
			locales: { root: { label: 'English', lang: 'en' } },
			social: [{ icon: 'github', label: 'GitHub', href: "https://github.com/akitaonrails/ai-memory" }],
			favicon: '/logo-light.png',
			sidebar: [
				{
					label: "Getting Started",
					items: [
					{ label: "ai-memory Docs", slug: 'index' },
					{ label: "Installation cookbook", slug: 'install' },
					{ label: "MCP install guide - additional clients", slug: 'mcp-install' },
					{ label: "Day-to-day usage", slug: 'usage' },
					],
				},
				{
					label: "Platforms",
					items: [
					{ label: "macOS Support", slug: 'macos' },
					{ label: "Windows Support", slug: 'windows' },
					{ label: "Shell completions", slug: 'shell-completions' },
					],
				},
				{
					label: "Deployment & Operations",
					items: [
					{ label: "Deploying ai-memory to a homelab", slug: 'deploy' },
					{ label: "HTTPS via a reverse proxy", slug: 'https-via-proxy' },
					{ label: "Lifecycle operations", slug: 'lifecycle-ops' },
					{ label: "Multi-user attribution", slug: 'users' },
					{ label: "LLM provider comparison - local Ollama vs hosted OpenRouter", slug: 'llm-provider-comparison' },
					{ label: "Vector Backend Policy", slug: 'vector-backend-policy' },
					],
				},
				{
					label: "Architecture & Design",
					items: [
					{ label: "ai-memory - Architecture", slug: 'architecture' },
					{ label: "ai-memory - Design Decisions (Synthesis)", slug: 'design-decisions' },
					{ label: "Optional companion crates and projects", slug: 'companion-crates' },
					{ label: "Marker file: `.ai-memory.toml`", slug: 'marker-file' },
					{ label: "Admission webhooks: pre-persistence HTTP hooks", slug: 'admission-webhooks' },
					{ label: "`[auto_scope]` isolation modes", slug: 'auto-scope' },
					{ label: "Wiki-structure migrations", slug: 'wiki-migrations' },
					{ label: "Frontend integration: `/api/v1`", slug: 'frontend-api' },
					],
				},
				{
					label: "Managed Workstreams",
					items: [
					{ label: "Managed cross-harness workstreams", slug: 'managed-workstreams' },
					{ label: "Adding a managed harness", slug: 'managed-harness-contributions' },
					],
				},
				{
					label: "Auto-Improve (Experimental)",
					items: [
					{ label: "Optional Auto-Improvement Loop Research", slug: 'auto-improvement-loop' },
					{ label: "Auto-Improve Eval Gates", slug: 'auto-improve-eval-gates' },
					{ label: "Auto-Improve Eval Example Scorers", slug: 'auto-improve-eval' },
					{ label: "Auto-Improve SkillOpt-Inspired Roadmap", slug: 'auto-improve-skillopt-roadmap' },
					],
				},
				{
					label: "Prior Art Research",
					items: [
					{ label: "Prior-Art Implementation Findings", slug: 'prior-art-implementation-findings' },
					{ label: "Karpathy's \\\"LLM Wiki\\\" - Research Report", slug: 'research-karpathy-llm-wiki' },
					{ label: "agentmemory - Research Report", slug: 'research-agentmemory' },
					{ label: "agentmemory - Issue & PR Pain-Point Synthesis", slug: 'issues-agentmemory' },
					{ label: "basic-memory - Research Report", slug: 'research-basic-memory' },
					{ label: "basic-memory - Issue & PR Pain-Point Synthesis", slug: 'issues-basic-memory' },
					{ label: "cognee - Research Report", slug: 'research-cognee' },
					{ label: "cognee - Issue & PR Pain-Point Synthesis", slug: 'issues-cognee' },
					{ label: "MemPalace - Issue & Architecture Synthesis", slug: 'issues-mempalace' },
					],
				},
				{
					label: "Project",
					items: [
					{ label: "v0.3 roadmap", slug: 'v03-roadmap' },
					],
				},
			],
		}),
	],
});
