// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// ai-memory Docs (English) — unofficial English mirror of https://github.com/akitaonrails/ai-memory
// Generated by scripts/new-en-mirror.cjs — do not edit content by hand; re-run to refresh.
export default defineConfig({
	site: undefined,
	base: process.env.DOCS_BASE || '/',
	integrations: [
		starlight({
			title: "ai-memory Docs (English)",
			description: "Unofficial English mirror of the ai-memory docs. Long-term memory for AI coding agents.",
			defaultLocale: 'root',
			locales: { root: { label: 'English', lang: 'en' } },
			social: [{ icon: 'github', label: 'GitHub', href: "https://github.com/akitaonrails/ai-memory" }],
			favicon: '/logo-light.png',
			sidebar: [{ label: 'Docs', items: [{ autogenerate: { directory: '' } }] }],
		}),
	],
});
