/**
 * Bundled registry index — auto-generated by
 * apps/www/scripts/generate-registry.ts. Do not edit by hand.
 *
 * Re-run via: pnpm --filter @nimbus/www generate-registry
 */

export type RegistryEntryType =
  | "registry:ui"
  | "registry:lib"
  | "registry:feature";

export interface RegistryIndexEntry {
  name: string;
  type: RegistryEntryType;
  title: string;
  description: string;
}

export interface BundledIndex {
  version: 1;
  registryVersion: string;
  items: Record<string, RegistryIndexEntry>;
}

export const REGISTRY_BASE_URL = "https://nimbus-docs.com/registry";

export const BUNDLED_INDEX: BundledIndex = {
  "version": 1,
  "registryVersion": "0.15.0",
  "items": {
    "cn": {
      "name": "cn",
      "type": "registry:lib",
      "title": "cn",
      "description": "Tailwind-aware className merger built on clsx + tailwind-merge."
    },
    "accordion": {
      "name": "accordion",
      "type": "registry:ui",
      "title": "Accordion",
      "description": "Vertically stacked collapsible sections."
    },
    "aside": {
      "name": "aside",
      "type": "registry:ui",
      "title": "Aside",
      "description": "Generic boxed callout — note, tip, caution, or danger."
    },
    "badge": {
      "name": "badge",
      "type": "registry:ui",
      "title": "Badge",
      "description": "Small status / category pill."
    },
    "banner": {
      "name": "banner",
      "type": "registry:ui",
      "title": "Banner",
      "description": "Site-wide dismissible announcement bar."
    },
    "breadcrumbs": {
      "name": "breadcrumbs",
      "type": "registry:ui",
      "title": "Breadcrumbs",
      "description": "Page-context navigation crumbs."
    },
    "button": {
      "name": "button",
      "type": "registry:ui",
      "title": "Button",
      "description": "Action trigger with variant/size/shape options. Owns the shared button/variants styling that LinkButton reuses."
    },
    "card": {
      "name": "card",
      "type": "registry:ui",
      "title": "Card",
      "description": "Generic content card with optional title and footer."
    },
    "card-grid": {
      "name": "card-grid",
      "type": "registry:ui",
      "title": "CardGrid",
      "description": "Responsive grid layout for cards."
    },
    "code": {
      "name": "code",
      "type": "registry:ui",
      "title": "Code",
      "description": "Inline / block code wrapper. Re-exports Astro's built-in <Code> (Shiki)."
    },
    "code-group": {
      "name": "code-group",
      "type": "registry:ui",
      "title": "CodeGroup",
      "description": "Tabbed group of code blocks."
    },
    "collapsible": {
      "name": "collapsible",
      "type": "registry:ui",
      "title": "Collapsible",
      "description": "Headless show/hide primitive — building block for Accordion and Sidebar groups."
    },
    "dialog": {
      "name": "dialog",
      "type": "registry:ui",
      "title": "Dialog",
      "description": "Modal dialog with focus-trap and body-scroll lock."
    },
    "embed": {
      "name": "embed",
      "type": "registry:ui",
      "title": "Embed",
      "description": "Responsive iframe / video / external content wrapper."
    },
    "file-tree": {
      "name": "file-tree",
      "type": "registry:ui",
      "title": "FileTree",
      "description": "Render a directory tree as nested markup."
    },
    "frame": {
      "name": "frame",
      "type": "registry:ui",
      "title": "Frame",
      "description": "Decorative outer frame for screenshots and demos."
    },
    "layer-card": {
      "name": "layer-card",
      "type": "registry:ui",
      "title": "LayerCard",
      "description": "Stacked-card container with sticky header. Base for CodeGroup and PackageManagers."
    },
    "link-button": {
      "name": "link-button",
      "type": "registry:ui",
      "title": "LinkButton",
      "description": "Anchor styled as a button. Shares styling with Button via button/variants."
    },
    "link-card": {
      "name": "link-card",
      "type": "registry:ui",
      "title": "LinkCard",
      "description": "Card whose entire surface is a link."
    },
    "package-managers": {
      "name": "package-managers",
      "type": "registry:ui",
      "title": "PackageManagers",
      "description": "Tabbed install command block translated across npm / pnpm / yarn / bun."
    },
    "page-actions": {
      "name": "page-actions",
      "type": "registry:ui",
      "title": "PageActions",
      "description": "Inline page-header actions: copy the page as markdown, open the raw .md."
    },
    "pagination": {
      "name": "pagination",
      "type": "registry:ui",
      "title": "Pagination",
      "description": "Prev / next page navigation."
    },
    "popover": {
      "name": "popover",
      "type": "registry:ui",
      "title": "Popover",
      "description": "Floating panel anchored to a trigger element."
    },
    "search": {
      "name": "search",
      "type": "registry:ui",
      "title": "Search",
      "description": "Command-palette search dialog with a provider seam. Defaults to Pagefind."
    },
    "sidebar": {
      "name": "sidebar",
      "type": "registry:ui",
      "title": "Sidebar",
      "description": "Docs sidebar with nested groups and active-link tracking."
    },
    "steps": {
      "name": "steps",
      "type": "registry:ui",
      "title": "Steps",
      "description": "Numbered ordered-list with vertical connectors."
    },
    "tabs": {
      "name": "tabs",
      "type": "registry:ui",
      "title": "Tabs",
      "description": "Tabbed content panels (manual + synced modes via syncKey)."
    },
    "theme-toggle": {
      "name": "theme-toggle",
      "type": "registry:ui",
      "title": "ThemeToggle",
      "description": "Light / dark theme switcher button."
    },
    "toc": {
      "name": "toc",
      "type": "registry:ui",
      "title": "TOC",
      "description": "On-page table of contents with active-heading tracking."
    },
    "version-switcher": {
      "name": "version-switcher",
      "type": "registry:ui",
      "title": "VersionSwitcher",
      "description": "Header dropdown for switching between docs versions. Reads `versions` from the Nimbus config, uses the build-time alternates table to land readers on the same logical page in the target version. Includes deprecation badge and hidden-version exclusion. Renders nothing when versioning is off or only one version is configured."
    },
    "api-field-row": {
      "name": "api-field-row",
      "type": "registry:ui",
      "title": "ApiFieldRow",
      "description": "One `ApiFieldView` rendered recursively, plus a titled `ApiFieldList` group. Type links, required/nullable/deprecated flags, constraints/enum/default/example, nested children with omitted-count. Anchored by the field's coordinate id. Reads the view-model only."
    },
    "api-sidebar": {
      "name": "api-sidebar",
      "type": "registry:ui",
      "title": "ApiSidebar",
      "description": "Reference-collection nav rail over `ApiNav`. The docs sidebar rendered from API data: it composes the shared `SidebarGroupHeader`/`SidebarLink` atoms and adds a co-located, self-scoped method chip on operation leaves. The tree math (active/expanded) lives in `getApiNav`."
    },
    "api-code-rail": {
      "name": "api-code-rail",
      "type": "registry:ui",
      "title": "ApiCodeRail",
      "description": "An operation's code rail: a `LayerCard` of server-provided code samples with a synced language switcher, headed by the method chip (`ApiMethodChip`) and operation title, plus a status toggle that swaps between response examples. Reads an `ApiOperationPage`."
    },
    "api-layout": {
      "name": "api-layout",
      "type": "registry:ui",
      "title": "ApiLayout",
      "description": "Three-column reference shell (nav · content · code rail) composing ApiSidebar + ApiFieldRow + ApiCodeRail. Renders any `ApiPageProps` by kind; widths inherit the site's layout tokens."
    },
    "diagram": {
      "name": "diagram",
      "type": "registry:lib",
      "title": "Diagram UI",
      "description": "React visual components for `nimbus-docs/react`'s headless <Diagram> wrapper: ActionBar, ActionButton (ghost + primary variants), ChipGroup, Tabs (uses useTabIndicator), DiagramControls (toolbar with status slot + pre-wired Play/Pause/Reset via useDiagram), DiagramDefs (shared SVG filter/marker defs), DiagramStage (bordered dotted-grid canvas + shared keyframes), CardBadge, DiagramDebug, DiagramPauseAll. Install when authoring interactive diagrams. Lifts as React, not Astro — kept paradigm-segregated under src/components/react/diagram/."
    },
    "diagram-scene": {
      "name": "diagram-scene",
      "type": "registry:lib",
      "title": "Diagram scene",
      "description": "Declarative card factory over `nimbus-docs/react`: author a diagram as data (phase steps, active-id table, edge specs) plus a CSS layout of labelled nodes. Measurement, edge routing, the SVG layer, and active-state styling are handled by the component — user-owned, restyle freely. `<Scene>` composes inside an existing <Diagram>; `createScene` wraps it into a standalone card. For pill-and-arrow diagrams; bespoke cards compose the hooks directly."
    },
    "404-page": {
      "name": "404-page",
      "type": "registry:feature",
      "title": "Custom 404 page",
      "description": "Generate a brand-matched 404 page for the docs site."
    },
    "ai-native": {
      "name": "ai-native",
      "type": "registry:feature",
      "title": "Markdown and llms.txt endpoints",
      "description": "Add alternate Markdown/MDX versions, llms.txt indexes, llms-full.txt, robots.txt, and an AgentDirective to a Nimbus docs site."
    },
    "api-reference": {
      "name": "api-reference",
      "type": "registry:feature",
      "title": "OpenAPI reference",
      "description": "Mount an OpenAPI (Swagger) spec as a routed reference collection with generated pages, alternate Markdown versions, and llms.txt indexes from one spec file. For hand-authored API docs written as MDX, use `new-collection` instead."
    },
    "changelog": {
      "name": "changelog",
      "type": "registry:feature",
      "title": "Changelog",
      "description": "Add a reverse-chronological changelog at /changelog — a dated timeline feed that renders full entries inline, with tag filtering, year-grouped load-more pagination, per-entry permalinks, OG cards, markdown alternates, and an optional RSS feed. Generic: tags are opaque strings you define. For a feed-style changelog; for a docs-shaped tree use `nimbus-docs add new-collection`."
    },
    "component-showcase": {
      "name": "component-showcase",
      "type": "registry:feature",
      "title": "Component showcase",
      "description": "Add a /components grid landing plus per-component showcase pages at /components/<slug>, driven by a dedicated content collection. For sites documenting their own UI library."
    },
    "content-changelog": {
      "name": "content-changelog",
      "type": "registry:feature",
      "title": "Recipe: Changelog",
      "description": "Write changelog entries — dated, categorized records that flag breakage and deep-link into the docs."
    },
    "content-concept": {
      "name": "content-concept",
      "type": "registry:feature",
      "title": "Recipe: Concept",
      "description": "Scaffold an understanding page — what a thing is, why it works that way, and where its boundaries are."
    },
    "content-example": {
      "name": "content-example",
      "type": "registry:feature",
      "title": "Recipe: Example",
      "description": "Scaffold a cookbook page — complete, runnable code the reader copies whole, with prose only for the non-obvious."
    },
    "content-how-to": {
      "name": "content-how-to",
      "type": "registry:feature",
      "title": "Recipe: How-to guide",
      "description": "Scaffold a task page — numbered steps that take a competent reader from a goal to a verified outcome."
    },
    "content-overview": {
      "name": "content-overview",
      "type": "registry:feature",
      "title": "Recipe: Overview",
      "description": "Scaffold a product-area landing page — orient the reader in one paragraph, then route them everywhere else."
    },
    "content-quickstart": {
      "name": "content-quickstart",
      "type": "registry:feature",
      "title": "Recipe: Quickstart",
      "description": "Scaffold a first-success page — the shortest honest path from nothing to one working result, with the output shown."
    },
    "content-reference": {
      "name": "content-reference",
      "type": "registry:feature",
      "title": "Recipe: Reference",
      "description": "Scaffold a lookup page — complete, neutral, rigidly templated, with the answer above the prose."
    },
    "content-troubleshooting": {
      "name": "content-troubleshooting",
      "type": "registry:feature",
      "title": "Recipe: Troubleshooting",
      "description": "Scaffold a failure page — verbatim symptoms, causes, and fixes, titled by what the reader pastes into search."
    },
    "content-tutorial": {
      "name": "content-tutorial",
      "type": "registry:feature",
      "title": "Recipe: Tutorial",
      "description": "Scaffold a lesson — numbered parts that build one real project, teacher-owned, every stage producing a visible result."
    },
    "lint-prose-textlint": {
      "name": "lint-prose-textlint",
      "type": "registry:feature",
      "title": "Prose linting with textlint",
      "description": "Add textlint with write-good, alex, and terminology rules — npm-native prose linting that runs alongside nimbus-docs lint."
    },
    "mermaid": {
      "name": "mermaid",
      "type": "registry:feature",
      "title": "Mermaid diagrams",
      "description": "Add lazy-loaded, theme-aware Mermaid.js diagram rendering with a skeleton loading state, safe color fallbacks, and a full-screen expand dialog."
    },
    "new-collection": {
      "name": "new-collection",
      "type": "registry:feature",
      "title": "Add a new collection",
      "description": "End-to-end setup for a non-version content tree on a Nimbus docs site — blog, API reference, changelog, glossary. Creates the folder, registers the collection, scaffolds routes. For docs versions, use `nimbus-docs add new-version`."
    },
    "new-version": {
      "name": "new-version",
      "type": "registry:feature",
      "title": "Add a docs version",
      "description": "End-to-end setup for adding a docs version to a Nimbus site. Creates the content directory, registers the collection, scaffolds routes, declares the manifest, installs the version-switcher picker, and wires it into your Header and DocsLayout. One command for one mental task."
    },
    "pagefind-search": {
      "name": "pagefind-search",
      "type": "registry:feature",
      "title": "Pagefind search",
      "description": "Add static Pagefind indexing and the Nimbus search dialog to an existing docs site."
    }
  }
};
